import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink, Quote } from "lucide-react";
import { fetchDocument, fetchFragments } from "@/lib/providers/indian-kanoon";

export default async function JudgmentReaderPage({ params, searchParams }: { params: Promise<{ tid: string }>; searchParams: Promise<{ q?: string }> }) {
  const { tid } = await params; const id = Number(tid); if (!Number.isInteger(id) || id <= 0) return notFound(); const query = (await searchParams).q?.slice(0, 200) ?? "";
  const result = await fetchDocument(id); if (!result) return notFound(); const fragments = query ? (await fetchFragments(id, query)).fragments : []; const doc = result.doc;
  return <div className="workspace-page !max-w-[100rem]"><Link href="/app/research" className="inline-flex items-center gap-1.5 text-xs font-semibold text-ink-500 hover:text-navy-950"><ArrowLeft className="h-3.5 w-3.5" /> Research results</Link><header className="mt-6 border-b border-ink-200 pb-6"><div className="flex flex-wrap items-center gap-2"><p className="eyebrow text-navy-700">Judgment reader</p><span className={`text-[10px] font-bold uppercase tracking-[0.12em] ${result.mode === "live" ? "text-verified-700" : "text-amber-700"}`}>{result.mode === "live" ? "Indian Kanoon source" : "Demo — not a legal source"}</span></div><h1 className="mt-3 max-w-5xl font-serif-display text-3xl leading-tight text-navy-950 sm:text-4xl">{doc.title}</h1><p className="mt-3 text-xs text-ink-500">{[doc.source, doc.doctype, doc.date, doc.caseNo].filter(Boolean).join(" · ")}</p></header><div className="mt-7 grid gap-7 xl:grid-cols-[minmax(0,1fr)_22rem]"><article className="document-surface p-6 sm:p-10"><pre className="mx-auto max-w-3xl whitespace-pre-wrap font-serif-display text-[15px] leading-8 text-ink-800">{doc.fullText || "No judgment text was returned."}</pre></article><aside className="space-y-4 xl:sticky xl:top-6 xl:self-start"><ReaderPanel title="Overview"><dl className="space-y-3 text-sm"><div><dt className="text-xs text-ink-400">Case number</dt><dd className="mt-1 text-ink-700">{doc.caseNo || "Not returned"}</dd></div><div><dt className="text-xs text-ink-400">Citations</dt><dd className="mt-1 text-ink-700">Cites {doc.numCites} · cited by {doc.numCitedBy}</dd></div></dl></ReaderPanel>{fragments.length ? <ReaderPanel title="Relevant passages"><div className="space-y-4">{fragments.map((fragment, index) => <blockquote key={index} className="border-l-2 border-navy-700 pl-3 text-xs leading-5 text-ink-600"><Quote className="mb-2 h-3.5 w-3.5 text-navy-700" /><span>{fragment}</span></blockquote>)}</div></ReaderPanel> : null}<a href={`https://indiankanoon.org/doc/${id}/`} target="_blank" rel="noreferrer" className="flex min-h-11 items-center justify-center gap-2 border border-ink-300 bg-white px-4 text-xs font-semibold text-navy-800">Open original source <ExternalLink className="h-3.5 w-3.5" /></a></aside></div></div>;
}
function ReaderPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="border border-ink-200 bg-white p-5"><h2 className="eyebrow text-navy-700">{title}</h2><div className="mt-3">{children}</div></section>; }
