"use client";

import Link from "next/link";
import { useState } from "react";
import { ChevronLeft, ChevronRight, ExternalLink, Search, SlidersHorizontal } from "lucide-react";

export interface ResearchHit { id: string; title: string; type: string; authority?: string; date?: string; citation?: string; excerpt?: string; url?: string; numCites?: number; numCitedBy?: number; mode: "live" | "mock"; }

export function CaseLawSearch() {
  const [query, setQuery] = useState(""); const [court, setCourt] = useState(""); const [act, setAct] = useState(""); const [section, setSection] = useState(""); const [fromdate, setFromdate] = useState(""); const [todate, setTodate] = useState(""); const [sortby, setSortby] = useState<"relevance" | "date">("relevance"); const [filtersOpen, setFiltersOpen] = useState(false);
  const [page, setPage] = useState(0); const [searching, setSearching] = useState(false); const [searched, setSearched] = useState(false); const [hits, setHits] = useState<ResearchHit[]>([]); const [hasMore, setHasMore] = useState(false); const [mode, setMode] = useState<"live" | "mock">("live"); const [error, setError] = useState<string | null>(null);
  const effectiveQuery = [query.trim(), court && `court: ${court}`, act && `act: ${act}`, section && `section ${section}`].filter(Boolean).join(" ");

  async function runSearch(nextPage: number) {
    if (!effectiveQuery || searching) return; setSearching(true); setError(null); setSearched(true);
    const params = new URLSearchParams({ q: effectiveQuery, page: String(nextPage) }); if (fromdate) params.set("fromdate", fromdate); if (todate) params.set("todate", todate); if (sortby === "date") params.set("sortby", "date");
    try { const response = await fetch(`/api/research?${params}`); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Search failed."); setHits(data.results); setMode(data.mode); setPage(data.page); setHasMore(data.hasMore); } catch (cause) { setError(cause instanceof Error ? cause.message : "Search failed."); } finally { setSearching(false); }
  }

  return <div>
    <form onSubmit={(event) => { event.preventDefault(); runSearch(0); }} className="document-surface border-t-2 border-t-navy-950 p-4 sm:p-6">
      <div className="flex items-center gap-3"><Search className="h-5 w-5 shrink-0 text-navy-800" /><label htmlFor="case-law-query" className="sr-only">Search Indian case law</label><input id="case-law-query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Case name, legal issue, citation, Act or section…" className="min-h-12 min-w-0 flex-1 bg-transparent font-serif-display text-lg text-navy-950 outline-none placeholder:text-ink-300 sm:text-xl" /><button type="button" onClick={() => setFiltersOpen((value) => !value)} aria-expanded={filtersOpen} className="inline-flex min-h-10 items-center gap-2 px-3 text-xs font-semibold text-ink-600 hover:text-navy-950"><SlidersHorizontal className="h-4 w-4" /><span className="hidden sm:inline">Filters</span></button><button disabled={searching || !effectiveQuery} className="min-h-11 bg-navy-950 px-5 text-sm font-semibold text-white disabled:opacity-40">{searching ? "Searching…" : "Search"}</button></div>
      {filtersOpen ? <div className="mt-5 grid gap-3 border-t border-ink-200 pt-5 sm:grid-cols-2 lg:grid-cols-6"><Filter label="Court / author" value={court} setValue={setCourt} /><Filter label="Act" value={act} setValue={setAct} /><Filter label="Section" value={section} setValue={setSection} /><DateFilter label="From" value={fromdate} setValue={setFromdate} /><DateFilter label="To" value={todate} setValue={setTodate} /><label className="text-[10px] font-bold uppercase tracking-[0.1em] text-ink-500">Sort<select value={sortby} onChange={(event) => setSortby(event.target.value as "relevance" | "date")} className="mt-1.5 min-h-10 w-full border border-ink-300 bg-white px-2 text-sm font-normal normal-case tracking-normal text-ink-700"><option value="relevance">Relevance</option><option value="date">Newest first</option></select></label></div> : null}
    </form>
    {error ? <p role="alert" className="mt-4 text-sm text-critical-600">{error}</p> : null}
    {mode === "mock" && hits.length ? <p className="mt-4 border-l-2 border-amber-600 bg-amber-100/40 px-4 py-3 text-xs text-amber-800">Live Indian Kanoon access is unavailable. These are demo results and must not be treated as legal sources.</p> : null}
    {searched && !searching && !error && !hits.length ? <div className="mt-8 border border-dashed border-ink-300 p-10 text-center"><p className="font-serif-display text-lg text-navy-950">No matching judgments</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-ink-500">Try broader wording, fewer filters, or a different Act or section. You can also search from within a Matter under <span className="font-semibold text-ink-700">Research</span> to keep results tied to it.</p><button type="button" onClick={() => { setQuery(""); setCourt(""); setAct(""); setSection(""); setFromdate(""); setTodate(""); setSearched(false); }} className="mt-5 inline-flex min-h-10 items-center border border-ink-300 px-4 text-xs font-semibold text-ink-600 hover:border-navy-700 hover:text-navy-950">Clear filters</button></div> : null}
    {hits.length ? <div className="mt-8"><div className="mb-3 flex items-center justify-between"><p className="eyebrow">Search results</p><span className="text-xs text-ink-400">Page {page + 1}</span></div><div className="border-t border-ink-300">{hits.map((hit) => { const tid = hit.id.replace("ik-", ""); return <article key={hit.id} className="border-b border-ink-200 py-6"><div className="grid gap-4 sm:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[0.12em] text-navy-700">{hit.authority ?? hit.type}</span><span className={`text-[10px] font-bold uppercase tracking-[0.1em] ${hit.mode === "live" ? "text-verified-700" : "text-amber-700"}`}>{hit.mode === "live" ? "Source available" : "Demo"}</span></div><h2 className="mt-2 font-serif-display text-xl text-navy-950 sm:text-2xl">{hit.title}</h2><p className="mt-2 text-xs text-ink-500">{[hit.date, hit.citation, hit.type].filter(Boolean).join(" · ")}</p>{hit.excerpt ? <p className="mt-4 max-w-4xl text-sm leading-6 text-ink-600 line-clamp-3">{hit.excerpt}</p> : null}</div><div className="flex items-start gap-2 sm:flex-col"><Link href={`/app/research/${tid}?q=${encodeURIComponent(query.trim())}`} className="inline-flex min-h-10 items-center justify-center bg-navy-950 px-4 text-xs font-semibold text-white">Open judgment</Link>{hit.url ? <a href={hit.url} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center justify-center gap-1 border border-ink-300 px-3 text-xs font-semibold text-ink-600">Original <ExternalLink className="h-3 w-3" /></a> : null}</div></div></article>; })}</div><div className="mt-6 flex items-center justify-between"><button disabled={page === 0 || searching} onClick={() => runSearch(page - 1)} className="inline-flex items-center gap-1 text-xs font-semibold text-navy-800 disabled:opacity-30"><ChevronLeft className="h-4 w-4" /> Previous</button><button disabled={!hasMore || searching} onClick={() => runSearch(page + 1)} className="inline-flex items-center gap-1 text-xs font-semibold text-navy-800 disabled:opacity-30">Next <ChevronRight className="h-4 w-4" /></button></div></div> : searched && !searching ? <div className="mt-8 border border-dashed border-ink-300 p-12 text-center text-sm text-ink-500">No matching legal records were returned.</div> : <div className="mt-8 grid gap-px bg-ink-200 sm:grid-cols-3">{["Search by legal issue", "Narrow by court or date", "Open the source judgment"].map((text, index) => <div key={text} className="bg-paper p-5"><span className="font-serif-display text-lg text-ink-300">0{index + 1}</span><p className="mt-2 text-xs font-semibold text-ink-600">{text}</p></div>)}</div>}
  </div>;
}

function Filter({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { return <label className="text-[10px] font-bold uppercase tracking-[0.1em] text-ink-500">{label}<input value={value} onChange={(event) => setValue(event.target.value)} className="mt-1.5 min-h-10 w-full border border-ink-300 bg-white px-2 text-sm font-normal normal-case tracking-normal text-ink-700" /></label>; }
function DateFilter({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { return <label className="text-[10px] font-bold uppercase tracking-[0.1em] text-ink-500">{label}<input type="date" value={value} onChange={(event) => setValue(event.target.value)} className="mt-1.5 min-h-10 w-full border border-ink-300 bg-white px-2 text-xs font-normal normal-case tracking-normal text-ink-700" /></label>; }
