import { notFound } from "next/navigation";
import { AlertCircle, CheckCircle2, FileQuestion } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { getMatterDetail } from "@/lib/matters/service";
import { buildEvidenceChecklist } from "@/lib/matters/evidence";

export default async function MatterEvidencePage({ params }: PageProps<"/app/matters/[id]/evidence">) { const user = await getCurrentUser(); if (!user) return notFound(); const { id } = await params; const matter = await getMatterDetail(user.id, id); if (!matter) return notFound(); const checklist = await buildEvidenceChecklist(id); return <div><header className="max-w-3xl"><p className="eyebrow text-navy-700">Evidence board</p><h2 className="mt-2 font-serif-display text-3xl text-navy-950">What supports the facts</h2><p className="mt-2 text-sm leading-6 text-ink-600">Items are connected to this Matter&apos;s legal route. “Potentially useful” is not the same as legally required.</p></header><div className="mt-8 grid gap-px bg-ink-200 lg:grid-cols-3"><EvidenceColumn title="Available" icon={<CheckCircle2 />} tone="text-verified-700" empty="No evidence is marked available yet.">{checklist.available.map((item) => <EvidenceItem key={item.title} title={item.title} note={`Source: ${item.source}`} />)}</EvidenceColumn><EvidenceColumn title="Potentially useful" icon={<FileQuestion />} tone="text-navy-700" empty="Attach a NyayPath to identify potentially useful material.">{checklist.missing.map((item) => <EvidenceItem key={item.title} title={item.title} note={item.whyRelevant} />)}</EvidenceColumn><EvidenceColumn title="Needs verification" icon={<AlertCircle />} tone="text-amber-700" empty="Nothing is currently flagged for verification.">{checklist.needsVerification.map((item) => <EvidenceItem key={item.title} title={item.title} note={item.note} />)}</EvidenceColumn></div><p className="mt-5 text-xs leading-5 text-ink-400">Evidence readiness describes what is stored in this workspace. It does not predict admissibility or outcome.</p></div>; }
function EvidenceColumn({ title, icon, tone, empty, children }: { title: string; icon: React.ReactNode; tone: string; empty: string; children: React.ReactNode[] }) { return <section className="min-h-80 bg-white p-5"><div className={`flex items-center gap-2 ${tone} [&_svg]:h-4 [&_svg]:w-4`}>{icon}<h3 className="text-[10px] font-bold uppercase tracking-[0.14em]">{title}</h3></div><div className="mt-5 space-y-3">{children.length ? children : <p className="text-sm leading-6 text-ink-400">{empty}</p>}</div></section>; }
function EvidenceItem({ title, note }: { title: string; note: string }) { return <div className="border-l-2 border-ink-200 bg-paper/60 px-3 py-2.5"><p className="text-sm font-semibold text-navy-950">{title}</p><p className="mt-1 text-xs leading-5 text-ink-500">{note}</p></div>; }
