"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Check, Download, Loader2, Printer, Save } from "lucide-react";

export function DraftEditor({ matterId, draft }: { matterId: string; draft: { id: string; title: string; content: string; status: "draft" | "review" | "final"; kind: string } }) {
  const router = useRouter(); const [title, setTitle] = useState(draft.title); const [content, setContent] = useState(draft.content); const [status, setStatus] = useState(draft.status); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState<string | null>(null);
  async function save(nextStatus = status) { setSaving(true); setError(null); setSaved(false); try { const response = await fetch(`/api/matters/${matterId}/drafts/${draft.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, content, status: nextStatus }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Could not save draft."); setStatus(nextStatus); setSaved(true); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save draft."); } finally { setSaving(false); } }
  function download() { const blob = new Blob([content], { type: "text/plain;charset=utf-8" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${title.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase() || "draft"}.txt`; link.click(); URL.revokeObjectURL(url); }
  return <div className="draft-workspace"><div className="print-control flex flex-wrap items-center gap-2 border-b border-ink-200 pb-4"><span className="mr-auto border border-amber-300 bg-amber-100/60 px-3 py-2 text-[10px] font-bold uppercase tracking-[0.12em] text-amber-800">Draft — review before use</span><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="min-h-10 border border-ink-300 bg-white px-3 text-xs font-semibold text-ink-700"><option value="draft">Draft</option><option value="review">Ready for review</option><option value="final">Final</option></select><button onClick={() => save()} disabled={saving} className="inline-flex min-h-10 items-center gap-2 bg-navy-950 px-4 text-xs font-semibold text-white disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : saved ? <Check className="h-4 w-4" /> : <Save className="h-4 w-4" />} {saved ? "Saved" : "Save"}</button><button onClick={() => window.print()} className="grid h-10 w-10 place-items-center border border-ink-300 bg-white" aria-label="Print draft"><Printer className="h-4 w-4" /></button><button onClick={download} className="grid h-10 w-10 place-items-center border border-ink-300 bg-white" aria-label="Download draft"><Download className="h-4 w-4" /></button></div>{error ? <p role="alert" className="mt-3 text-sm text-critical-600">{error}</p> : null}<div className="document-surface mx-auto mt-7 max-w-4xl p-7 sm:p-12"><label htmlFor="draft-title" className="sr-only">Draft title</label><input id="draft-title" value={title} onChange={(event) => { setTitle(event.target.value); setSaved(false); }} className="w-full border-b border-ink-300 bg-transparent pb-4 text-center font-serif-display text-2xl text-navy-950 outline-none" /><label htmlFor="draft-content" className="sr-only">Draft content</label><textarea id="draft-content" value={content} onChange={(event) => { setContent(event.target.value); setSaved(false); }} className="mt-8 min-h-[55rem] w-full resize-y bg-transparent font-serif-display text-[15px] leading-8 text-ink-800 outline-none" /></div></div>;
}
